### ISSUE TITLE
Switch to Fork Awesome?

### ISSUE THREAD

**Issue by elboulangero** [jvanz/pelican-hyde#16]
From `v5` onward, Font Awesome is not Free Software anymore. While the source code, and the built icon set, are freely available, the build toolchain is private and is not distributed. In effect, users can't modify Font Awesome for their needs, as they can't rebuild the font with their modification. That's my understanding of the situation after reading:

- https://bugs.dehttps://forkaweso.me/Fork-Awesome/examples/bian.org/cgi-bin/bugreport.cgi?bug=902981
- https://github.com/FortAwesome/Font-Awesome/issues/13467

So I would suggest to switch to Fork Awesome instead. However that means reverting !12 from @schneiderfelipe.

@schneiderfelipe do you really need v5 and the `kits` thing from Font Awesome? Or did you just update for the sake of being up to date?

**Comment by schneiderfelipe** [comment]
@elboulangero Yes, some icons are only available in the new version (5+), but I would be happy with any good icon set. Is ForkAwesome a drop-in replacement?

**Comment by elboulangero** [comment]
@schneiderfelipe Fork Awesome is a drop-in replacement for `v4`, but is not compatible with `v5`, since Font Awesome broke compatibility in v5. As you've seen, they introduced the css classes `fab` (b for "brand") , `fas` (f for ... something), and they dropped `fa`. While Fork Awesome only uses the classes `fa` like in v4. They do provide a compatibility layer though.

Also, one reason that Fork Awesome was forked out of Font Awesome is to actually provide more icons. Apparently FA stopped accepting Pull Requests a while ago, and contributors where frustrated. So Fork Awesome was created to be more community oriented, and is more willing to accepts new icons.

You can find details in those discussions:
- https://github.com/ForkAwesome/Fork-Awesome
- https://github.com/FortAwesome/Font-Awesome/issues/12199#issuecomment-362919956

Personally, I use Fork Awesome because it has the icons I want, and for the icons that are missing, I can add it and submit a pull request.

But for the `pelican-hyde` theme, I think the question is more along the lines of:
- do we want to use an icon theme that is really free software -> then Fork Awesome seems more suitable, and it's packaged in Debian
- do we just want the latest from Font Awesome, and we don't care about free software

**Comment by schneiderfelipe** [comment]
> @schneiderfelipe Fork Awesome is a drop-in replacement for `v4`, but is not compatible with `v5`, since Font Awesome broke compatibility in v5. As you've seen, they introduced the css classes `fab` (b for "brand") , `fas` (f for ... something), and they dropped `fa`. While Fork Awesome only uses the classes `fa` like in v4. They do provide a compatibility layer though.
> 
> Also, one reason that Fork Awesome was forked out of Font Awesome is to actually provide more icons. Apparently FA stopped accepting Pull Requests a while ago, and contributors where frustrated. So Fork Awesome was created to be more community oriented, and is more willing to accepts new icons.

Excellent, I personally don't care about being compatible with `v5`, I just want the icons.

> Personally, I use Fork Awesome because it has the icons I want, and for the icons that are missing, I can add it and submit a pull request.

Seems good. I've checked and they have most of the icons I need, so no problem there.

> * do we want to use an icon theme that is really free software -> then Fork Awesome seems more suitable, and it's packaged in Debian

I would go for this one. @jvanz what are your thoughts on this?

**Comment by schneiderfelipe** [comment]
(By the way, thanks for letting me know about those issues @elboulangero!)

**Comment by jvanz** [comment]
I  prefer go with the free software  option.

**Comment by elboulangero** [comment]
@jvanz Alright so this change is now included in the lengthy PR https://github.com/jvanz/pelican-hyde/pull/15

**Comment by jvanz** [comment]
I've merged the PR. Closing this issue.
