### ISSUE TITLE
Google Analytics 4 support

### ISSUE THREAD

**Issue by geokats7** [jvanz/pelican-hyde#22]
I noticed that if you choose to integrate google analytics with their new version the current implementation doesn't seem to work.
Now, the `google_analytics.html` has the following script which supports only the "Universal Analytics":

```html
{% if GOOGLE_ANALYTICS %}
<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', '{{ GOOGLE_ANALYTICS }}', '{{ GA_COOKIE_DOMAIN if GA_COOKIE_DOMAIN else 'auto' }}');
ga('send', 'pageview');
</script>
{% endif %}
```
while the new version of Google Analytics 4 [instructs](https://support.google.com/analytics/answer/9304153?hl=en&ref_topic=9303319) to use the following snippet:
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS }}');
</script>
```
I have tested the latter snippet and it works.
If you want I could open a PR to support the new analytics as well.
Let me know.

**Comment by jvanz** [comment]
Hi @geokats7!

Please, open a PR. Thank you!

**Comment by geokats7** [comment]
Hi @jvanz, it's been quite a while since a checked this so probably I need to have a look again.
I'll try to find time within the next weeks.

**Comment by jvanz** [comment]
> Hi @jvanz, it's been quite a while since a checked this so probably I need to have a look again. I'll try to find time within the next weeks.

Sorry for the long delay to give you a feedback.
