### ISSUE TITLE
How to pass BIO

### ISSUE THREAD

**Issue by canyon289** [jvanz/pelican-hyde#5]
Hi,
I see this line in sidebar.html

```
        <p class="lead">{{ BIO }} </p>
```

I was wondering where do I place the BIO string so jinja places it in the template?

Thanks for this awesome theme!

**Comment by jvanz** [comment]
Hi! Sorry for delay. 

You should put the BIO string in the publishconf.py. Take a look in following example:
https://github.com/jvanz/jvanz.github.io-src/blob/master/publishconf.py#L59

Thanks!
